import streamlit as st
import numpy as np
import cv2
from PIL import Image
import torch
from transformers import pipeline

# -------------------------------------------------------------
# 1. AI: KHỞI TẠO MODEL TẠO DEPTH MAP (Depth Anything V2)
# -------------------------------------------------------------
@st.cache_resource
def load_depth_ai():
    pipe = pipeline(task="depth-estimation", model="depth-anything/Depth-Anything-V2-Small-hf")
    return pipe

# -------------------------------------------------------------
# 2. HÀM VẼ MÔ PHỎNG VỊ TRÍ TRANH TRÊN VÁN (CANVAS 2D)
# -------------------------------------------------------------
def draw_preview_canvas(sheet_w, sheet_h, pic_w, pic_h, origin_point):
    canvas_w = 600
    canvas_h = int(600 * (sheet_h / sheet_w)) if sheet_w > 0 else 600
    canvas = np.ones((canvas_h, canvas_w, 3), dtype=np.uint8) * 230
    
    scale = canvas_w / sheet_w
    pw = int(pic_w * scale)
    ph = int(pic_h * scale)
    
    if origin_point == "Center (Tâm phôi)":
        px = int((sheet_w / 2.0 - pic_w / 2.0) * scale)
        py = int((sheet_h / 2.0 - pic_h / 2.0) * scale)
    elif origin_point == "Top-Left (Góc trên - Trái)":
        px, py = 0, 0
    elif origin_point == "Top-Right (Góc trên - Phải)":
        px, py = int((sheet_w - pic_w) * scale), 0
    elif origin_point == "Bottom-Right (Góc dưới - Phải)":
        px, py = int((sheet_w - pic_w) * scale), int((sheet_h - pic_h) * scale)
    else:  # Bottom-Left
        px, py = 0, int((sheet_h - pic_h) * scale)
        
    cv2.rectangle(canvas, (0, 0), (canvas_w - 1, canvas_h - 1), (100, 100, 100), 2)
    cv2.rectangle(canvas, (px, py), (px + pw, py + ph), (34, 139, 34), -1)
    cv2.rectangle(canvas, (px, py), (px + pw, py + ph), (0, 100, 0), 2)
    
    if origin_point == "Center (Tâm phôi)":
        ox, oy = int(canvas_w / 2.0), int(canvas_h / 2.0)
    elif origin_point == "Top-Left (Góc trên - Trái)":
        ox, oy = 0, 0
    elif origin_point == "Top-Right (Góc trên - Phải)":
        ox, oy = canvas_w, 0
    elif origin_point == "Bottom-Right (Góc dưới - Phải)":
        ox, oy = canvas_w, canvas_h
    else:  # Bottom-Left
        ox, oy = 0, canvas_h
        
    cv2.circle(canvas, (ox, oy), 8, (0, 0, 255), -1)
    cv2.putText(canvas, "X0 Y0", (ox + 10, oy - 10 if oy > 20 else oy + 20), 
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)

    return canvas

# -------------------------------------------------------------
# 3. HÀM TẠO G-CODE CÓ TỰ ĐỘNG BÙ DAO CẮT VIỀN RIÊNG
# -------------------------------------------------------------
def generate_grbl_gcode(depth_map, width_mm, height_mm, max_depth_mm, 
                        feed_rate, safe_z, stepover_mm, origin_point, 
                        process_mode, cut_depth_target, stepdown_mm, cutout_tool_dia):
    
    y_steps = int(height_mm / stepover_mm)
    x_steps = int(width_mm / stepover_mm)
    
    depth_resized = cv2.resize(depth_map, (x_steps, y_steps), interpolation=cv2.INTER_CUBIC)
    z_matrix = -1.0 * (1.0 - (depth_resized / 255.0)) * max_depth_mm

    # OFFSETS TỌA ĐỘ THEO GỐC CHỌN
    if origin_point == "Center (Tâm phôi)":
        x_offset = width_mm / 2.0
        y_offset = height_mm / 2.0
    elif origin_point == "Top-Left (Góc trên - Trái)":
        x_offset = 0.0
        y_offset = height_mm
    elif origin_point == "Top-Right (Góc trên - Phải)":
        x_offset = width_mm
        y_offset = height_mm
    elif origin_point == "Bottom-Right (Góc dưới - Phải)":
        x_offset = width_mm
        y_offset = 0.0
    else:  # Bottom-Left
        x_offset = 0.0
        y_offset = 0.0

    gcode = []
    # --- HEADER G-CODE ---
    gcode.append("(--- G-CODE GENERATED BY AI CNC DASHBOARD ---)")
    gcode.append(f"(--- Che do phay: {process_mode} ---)")
    gcode.append(f"(--- Origin Position: {origin_point} ---)")
    gcode.append("G21          ; Don vi: mm")
    gcode.append("G90          ; Toa do tuyet doi")
    gcode.append("M03 S12000   ; Bat truc chinh 12000 RPM")
    gcode.append(f"G00 Z{safe_z:.2f} ; Nhac dao an toan")
    gcode.append(f"G00 X0 Y0    ; Ve Goc X0 Y0")
    gcode.append(f"G01 F{feed_rate}  ; Thiet lap Feedrate")

    # --- 1. CHẠY PHAY 3D PHÙ ĐIÊU ---
    if process_mode in ["Chỉ Phay 3D (Dao cầu)", "Cả Phay 3D + Cắt đứt viền"]:
        gcode.append("(--- BAT DAU PHAY 3D ---)")
        for y_idx in range(y_steps):
            y_raw = (y_idx / (y_steps - 1)) * height_mm if y_steps > 1 else 0.0
            y_pos = y_raw - y_offset
            
            x_range = range(x_steps) if y_idx % 2 == 0 else range(x_steps - 1, -1, -1)
            
            for x_idx in x_range:
                x_raw = (x_idx / (x_steps - 1)) * width_mm if x_steps > 1 else 0.0
                x_pos = x_raw - x_offset
                z_pos = z_matrix[y_idx, x_idx]
                
                gcode.append(f"G01 X{x_pos:.3f} Y{y_pos:.3f} Z{z_pos:.3f}")

        gcode.append(f"G00 Z{safe_z:.2f} ; Hoan thanh Phay 3D")

    # --- 2. CHẠY CẮT ĐỨT VIỀN (BÙ BÁN KÍNH DAO CẮT VIỀN NGUYÊN BẢN) ---
    if process_mode in ["Chỉ Cắt Đứt Viền (Thay dao ngón)", "Cả Phay 3D + Cắt đứt viền"]:
        gcode.append("(--- BAT DAU PHAY CAT DUT VIEN TRANH (OUTSIDE OFFSET) ---)")
        
        # BÁN KÍNH DAO CẮT VIỀN RIÊNG
        cutout_radius = cutout_tool_dia / 2.0  
        
        # Tự động bù dao: Mở rộng viền cắt ra ngoài đúng bằng bán kính dao cắt
        x_min = -x_offset - cutout_radius
        x_max = (width_mm - x_offset) + cutout_radius
        y_min = -y_offset - cutout_radius
        y_max = (height_mm - y_offset) + cutout_radius
        
        # Di chuyển đến điểm bắt đầu đã bù dao
        gcode.append(f"G00 X{x_min:.3f} Y{y_min:.3f}")
        
        # Lập trình cắt nhiều lượt (Stepdown)
        current_z = 0.0
        while current_z < cut_depth_target:
            current_z += stepdown_mm
            if current_z > cut_depth_target:
                current_z = cut_depth_target  
                
            gcode.append(f"G01 Z{-current_z:.3f} F{max(300, feed_rate // 2)}")
            gcode.append(f"G01 X{x_max:.3f} Y{y_min:.3f} F{feed_rate}")
            gcode.append(f"G01 X{x_max:.3f} Y{y_max:.3f}")
            gcode.append(f"G01 X{x_min:.3f} Y{y_max:.3f}")
            gcode.append(f"G01 X{x_min:.3f} Y{y_min:.3f}")
            
        gcode.append(f"G00 Z{safe_z:.2f} ; Hoan thanh Cat Vien")

    # --- FOOTER ---
    gcode.append("G00 X0 Y0    ; Tro ve X0 Y0")
    gcode.append("M05          ; Tat truc chinh")
    gcode.append("M30          ; Ket thuc chuong trinh")
    
    return "\n".join(gcode)

# -------------------------------------------------------------
# 4. GIAO DIỆN DASHBOARD STREAMLIT
# -------------------------------------------------------------
st.set_page_config(page_title="AI CNC G-Code Generator", layout="wide")
st.title("🖼️ AI Tranh Gỗ 3D ➔ Tự Động Xuất G-Code (GRBL/UGS)")

col1, col2 = st.columns([1, 2])

with col1:
    st.header("1. Cấu hình Ván & Tranh")
    uploaded_file = st.file_uploader("📂 Tải ảnh tranh gỗ (JPG/PNG)", type=['jpg', 'png', 'jpeg'])
    
    st.subheader("📋 Kích thước Khổ Ván / Phôi Gỗ (mm)")
    sheet_w = st.number_input("Chiều rộng khổ ván (X - mm)", value=1200.0, step=100.0)
    sheet_h = st.number_input("Chiều dài khổ ván (Y - mm)", value=2400.0, step=100.0)
    sheet_thick_mm = st.number_input("Độ dày phôi ván (mm)", value=18.0, step=1.0)

    st.subheader("🖼️ Kích thước Bức Phù Điêu (mm)")
    width_mm = st.number_input("Chiều rộng bức tranh (X - mm)", value=200.0, step=10.0)
    height_mm = st.number_input("Chiều cao bức tranh (Y - mm)", value=300.0, step=10.0)
    max_depth_mm = st.number_input("Độ sâu đục 3D tối đa (Z - mm)", value=8.0, step=0.5)

    st.subheader("⚙️ Chế Độ Gia Công & Gốc Tọa Độ")
    process_mode = st.radio(
        "🛠️ Chọn chế độ xuất file G-code:",
        [
            "Chỉ Phay 3D (Dao cầu)",
            "Chỉ Cắt Đứt Viền (Thay dao ngón)",
            "Cả Phay 3D + Cắt đứt viền"
        ]
    )

    origin_point = st.selectbox(
        "📍 Vị trí Gốc Tọa Độ (Work Zero):",
        [
            "Bottom-Left (Góc dưới - Trái)",
            "Center (Tâm phôi)",
            "Top-Left (Góc trên - Trái)",
            "Bottom-Right (Góc dưới - Phải)",
            "Top-Right (Góc trên - Phải)"
        ]
    )

    # ĐÃ TÁCH RIÊNG CẤU HÌNH DAO CẮT VIỀN
    st.subheader("✂️ Cấu hình Cắt Viền (Cutout Profile)")
    cutout_tool_dia = st.number_input("Đường kính dao CẮT VIỀN (mm)", value=6.0, step=0.5)
    cut_depth_target = st.number_input("Tổng độ sâu cắt viền đứt phôi (Z - mm)", value=sheet_thick_mm + 0.5, step=0.5)
    stepdown_mm = st.number_input("Độ sâu ăn dao mỗi lượt/pass (mm)", value=4.0, step=0.5)

    st.subheader("🛠️ Thông số Dao Phay 3D & Tốc Độ Máy")
    tool_dia = st.number_input("Đường kính DAO CẦU đục 3D (mm)", value=3.175, step=0.1)
    stepover_pct = st.slider("Độ dịch dao phay 3D (Stepover %)", 10, 50, 15)
    feed_rate = st.number_input("Tốc độ phay F (mm/phút)", value=1500, step=100)
    safe_z = st.number_input("Chiều cao nhấc dao an toàn Z (mm)", value=5.0, step=1.0)
    
    btn_process = st.button("🚀 AI Xử Lý & Tạo G-Code", type="primary")

with col2:
    st.header("2. Hiển Thị & AI Xem Trước")
    
    if uploaded_file is not None:
        raw_image = Image.open(uploaded_file).convert('RGB')
        st.subheader("📷 Ảnh gốc vừa tải lên:")
        st.image(raw_image, caption="Ảnh gốc chuẩn bị dựng tranh 3D", use_column_width=True)
    else:
        st.info("👆 Vui lòng tải một bức ảnh ở cột bên trái để bắt đầu.")

    if width_mm > sheet_w or height_mm > sheet_h:
        st.error("⚠️ LỖI CẢNH BÁO: Kích thước bức tranh đang LỚN HƠN khổ ván! Vui lòng điều chỉnh lại.")
    else:
        st.subheader("📐 Mô phỏng vị trí Tranh (Xanh) trên Ván (Xám):")
        canvas_img = draw_preview_canvas(sheet_w, sheet_h, width_mm, height_mm, origin_point)
        st.image(canvas_img, caption="Chấm màu Đỏ đánh dấu vị trí Set Zero (X0 Y0)", use_column_width=True)

    if uploaded_file is not None and btn_process:
        with st.spinner("AI đang xử lý làm nét & trích xuất độ sâu 3D..."):
            depth_pipe = load_depth_ai()
            depth_out = depth_pipe(raw_image)["depth"]
            
            depth_np = np.array(depth_out)
            depth_resized = cv2.normalize(depth_np, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
            
            st.subheader("🖼️ Bản đồ độ sâu 3D (AI Depth Map):")
            st.image(depth_resized, caption="Màu Trắng = Nổi cao nhất, Màu Đen = Đục sâu nhất", use_column_width=True)
            
            stepover_mm = tool_dia * (stepover_pct / 100.0)
            
            gcode_txt = generate_grbl_gcode(
                depth_resized, width_mm, height_mm, max_depth_mm, 
                feed_rate, safe_z, stepover_mm, origin_point,
                process_mode, cut_depth_target, stepdown_mm, cutout_tool_dia
            )
            
            st.success(f"🎉 TẠO G-CODE THÀNH CÔNG! (Chế độ: {process_mode})")
            
            if process_mode == "Chỉ Phay 3D (Dao cầu)":
                file_name_out = "phay_3d.nc"
            elif process_mode == "Chỉ Cắt Đứt Viền (Thay dao ngón)":
                file_name_out = "cat_vien.nc"
            else:
                file_name_out = "phay_3d_va_cat_vien.nc"

            st.download_button(
                label=f"💾 Tải File G-code ({file_name_out}) Cho UGS",
                data=gcode_txt,
                file_name=file_name_out,
                mime="text/plain"
            )
